#!/bin/bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PATH="$HOME/.cargo/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"
exec "$HOME/Applications/Divvun-SEE-helper.app/Contents/MacOS/divvun-see-helper" "$@"
